import FiberFunction from "./fiber_function.ts";
import { FiberType, FiberValue } from "./fiber_value.ts";

export default class FiberModule {
    private name: string;
    private functions: FiberFunction[] = [];

    constructor(name: string = "main.fir") {
        this.name = name;
    }

    makeValue(
        value: string = "",
        pointer: string = "",
        isPointer: boolean = false,
        type: FiberType = FiberType.Void,
    ): FiberValue {
        return { value, pointer, isPointer, type };
    }

    addFunc(func: FiberFunction): void {
        this.functions.push(func);
    }

    gen(): string {
        let code = `// ${this.name} - Generated by FiberApi\n`;
        code += "// MIT LICENSE - Copyright (c) 2025 Fernando\n\n";
        code += this.functions.map((f) => f.gen()).join("\n");
        return code;
    }
}
