module lib.d.fiber_module;

import std.stdio;
import std.conv;
import std.array;
import std.algorithm;
import std.format;
import lib.d.fiber_function;

class FiberModule
{
private:
    string name;
    FiberFunction[] functions;
public:
    this(string name = "main.fir")
    {
        this.name = name;
    }

    void addFunc(FiberFunction func)
    {
        this.functions ~= func;
    }

    string gen()
    {
        string code = format("// %s - Generated by FiberApi\n", name);
        code ~= "// MIT LICENSE - Copyright (c) 2025 Fernando\n\n";
        code ~= functions.map!(f => f.gen()).array.join("\n");
        return code;
    }
}
